version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn --workers 3 --timeout 120 --bind 0.0.0.0:8000 userservice.wsgi:application
      "
    volumes:
      - .:/src
    working_dir: /src
    ports:
      - "8000:8000"
    depends_on:
      - db

  api:
    build: ./src
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.4.11
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - "3306:3306"

secrets:
  mysql_root_password:
    external: true
  mysql_database:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
