apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: userservice
        image: userservice:latest
        ports:
        - containerPort: 5000
