apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: userservice-web:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            python userservice/manage.py makemigrations &&
            python userservice/manage.py migrate &&
            gunicorn --workers 3 --timeout 120 --bind 0.0.0.0:8000 userservice.wsgi:application
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DB_PORT
          value: "3306"

      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
